#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 66
#define LARGE_STATE_COUNT 9
#define SYMBOL_COUNT 35
#define ALIAS_COUNT 0
#define TOKEN_COUNT 16
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_preserved = 2,
  anon_sym_COLON = 3,
  anon_sym_SEMI = 4,
  anon_sym_min = 5,
  anon_sym_max = 6,
  anon_sym_GT_EQ = 7,
  anon_sym_LT_EQ = 8,
  anon_sym_EQ = 9,
  anon_sym_EQ_EQ_GT = 10,
  anon_sym_LT_EQ_EQ = 11,
  anon_sym_TILDE = 12,
  sym_label = 13,
  sym_signed_integer = 14,
  sym_comment = 15,
  sym_source_file = 16,
  sym_preserved_directive = 17,
  sym_objective = 18,
  sym_objective_type = 19,
  sym__constraint = 20,
  sym_constraint_labelled = 21,
  sym_constraint_unlabelled = 22,
  sym_relational_operator = 23,
  sym_xpb_relational_operator = 24,
  sym_reification = 25,
  sym_sum = 26,
  sym_weighted_term = 27,
  sym_coefficient = 28,
  sym_literal = 29,
  sym_variable = 30,
  aux_sym_source_file_repeat1 = 31,
  aux_sym_preserved_directive_repeat1 = 32,
  aux_sym_reification_repeat1 = 33,
  aux_sym_sum_repeat1 = 34,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_preserved] = "preserved",
  [anon_sym_COLON] = ":",
  [anon_sym_SEMI] = ";",
  [anon_sym_min] = "min",
  [anon_sym_max] = "max",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_EQ] = "=",
  [anon_sym_EQ_EQ_GT] = "==>",
  [anon_sym_LT_EQ_EQ] = "<==",
  [anon_sym_TILDE] = "~",
  [sym_label] = "label",
  [sym_signed_integer] = "signed_integer",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym_preserved_directive] = "preserved_directive",
  [sym_objective] = "objective",
  [sym_objective_type] = "objective_type",
  [sym__constraint] = "_constraint",
  [sym_constraint_labelled] = "constraint_labelled",
  [sym_constraint_unlabelled] = "constraint_unlabelled",
  [sym_relational_operator] = "relational_operator",
  [sym_xpb_relational_operator] = "xpb_relational_operator",
  [sym_reification] = "reification",
  [sym_sum] = "sum",
  [sym_weighted_term] = "weighted_term",
  [sym_coefficient] = "coefficient",
  [sym_literal] = "literal",
  [sym_variable] = "variable",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_preserved_directive_repeat1] = "preserved_directive_repeat1",
  [aux_sym_reification_repeat1] = "reification_repeat1",
  [aux_sym_sum_repeat1] = "sum_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_preserved] = anon_sym_preserved,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_min] = anon_sym_min,
  [anon_sym_max] = anon_sym_max,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_EQ_EQ_GT] = anon_sym_EQ_EQ_GT,
  [anon_sym_LT_EQ_EQ] = anon_sym_LT_EQ_EQ,
  [anon_sym_TILDE] = anon_sym_TILDE,
  [sym_label] = sym_label,
  [sym_signed_integer] = sym_signed_integer,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym_preserved_directive] = sym_preserved_directive,
  [sym_objective] = sym_objective,
  [sym_objective_type] = sym_objective_type,
  [sym__constraint] = sym__constraint,
  [sym_constraint_labelled] = sym_constraint_labelled,
  [sym_constraint_unlabelled] = sym_constraint_unlabelled,
  [sym_relational_operator] = sym_relational_operator,
  [sym_xpb_relational_operator] = sym_xpb_relational_operator,
  [sym_reification] = sym_reification,
  [sym_sum] = sym_sum,
  [sym_weighted_term] = sym_weighted_term,
  [sym_coefficient] = sym_coefficient,
  [sym_literal] = sym_literal,
  [sym_variable] = sym_variable,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_preserved_directive_repeat1] = aux_sym_preserved_directive_repeat1,
  [aux_sym_reification_repeat1] = aux_sym_reification_repeat1,
  [aux_sym_sum_repeat1] = aux_sym_sum_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_preserved] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_min] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_max] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TILDE] = {
    .visible = true,
    .named = false,
  },
  [sym_label] = {
    .visible = true,
    .named = true,
  },
  [sym_signed_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_preserved_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_objective] = {
    .visible = true,
    .named = true,
  },
  [sym_objective_type] = {
    .visible = true,
    .named = true,
  },
  [sym__constraint] = {
    .visible = false,
    .named = true,
  },
  [sym_constraint_labelled] = {
    .visible = true,
    .named = true,
  },
  [sym_constraint_unlabelled] = {
    .visible = true,
    .named = true,
  },
  [sym_relational_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_xpb_relational_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_reification] = {
    .visible = true,
    .named = true,
  },
  [sym_sum] = {
    .visible = true,
    .named = true,
  },
  [sym_weighted_term] = {
    .visible = true,
    .named = true,
  },
  [sym_coefficient] = {
    .visible = true,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_preserved_directive_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_reification_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_sum_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 26,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(12);
      ADVANCE_MAP(
        '*', 27,
        '0', 25,
        ':', 13,
        ';', 14,
        '<', 3,
        '=', 19,
        '>', 5,
        '@', 10,
        '~', 22,
        '+', 2,
        '-', 2,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 1:
      if (lookahead == '*') ADVANCE(27);
      if (lookahead == '<') ADVANCE(8);
      if (lookahead == '=') ADVANCE(4);
      if (lookahead == '~') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 2:
      if (lookahead == '0') ADVANCE(25);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(26);
      END_STATE();
    case 3:
      if (lookahead == '=') ADVANCE(17);
      END_STATE();
    case 4:
      if (lookahead == '=') ADVANCE(9);
      END_STATE();
    case 5:
      if (lookahead == '=') ADVANCE(15);
      END_STATE();
    case 6:
      if (lookahead == '=') ADVANCE(21);
      END_STATE();
    case 7:
      if (lookahead == '=') ADVANCE(16);
      END_STATE();
    case 8:
      if (lookahead == '=') ADVANCE(6);
      END_STATE();
    case 9:
      if (lookahead == '>') ADVANCE(20);
      END_STATE();
    case 10:
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          (']' <= lookahead && lookahead <= '_') ||
          ('a' <= lookahead && lookahead <= '{') ||
          lookahead == '}') ADVANCE(24);
      END_STATE();
    case 11:
      if (eof) ADVANCE(12);
      ADVANCE_MAP(
        '*', 27,
        '0', 25,
        ';', 14,
        '<', 7,
        '=', 18,
        '>', 5,
        '@', 10,
        '~', 22,
        '+', 2,
        '-', 2,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(11);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      if (lookahead == '=') ADVANCE(21);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(9);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_EQ_EQ_GT);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LT_EQ_EQ);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_TILDE);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          (']' <= lookahead && lookahead <= '_') ||
          ('a' <= lookahead && lookahead <= '{') ||
          lookahead == '}') ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_label);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          (']' <= lookahead && lookahead <= '_') ||
          ('a' <= lookahead && lookahead <= '{') ||
          lookahead == '}') ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_signed_integer);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_signed_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(27);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'm') ADVANCE(1);
      if (lookahead == 'p') ADVANCE(2);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'a') ADVANCE(3);
      if (lookahead == 'i') ADVANCE(4);
      END_STATE();
    case 2:
      if (lookahead == 'r') ADVANCE(5);
      END_STATE();
    case 3:
      if (lookahead == 'x') ADVANCE(6);
      END_STATE();
    case 4:
      if (lookahead == 'n') ADVANCE(7);
      END_STATE();
    case 5:
      if (lookahead == 'e') ADVANCE(8);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_max);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_min);
      END_STATE();
    case 8:
      if (lookahead == 's') ADVANCE(9);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(10);
      END_STATE();
    case 10:
      if (lookahead == 'r') ADVANCE(11);
      END_STATE();
    case 11:
      if (lookahead == 'v') ADVANCE(12);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(13);
      END_STATE();
    case 13:
      if (lookahead == 'd') ADVANCE(14);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_preserved);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 11},
  [2] = {.lex_state = 11},
  [3] = {.lex_state = 11},
  [4] = {.lex_state = 11},
  [5] = {.lex_state = 11},
  [6] = {.lex_state = 11},
  [7] = {.lex_state = 11},
  [8] = {.lex_state = 11},
  [9] = {.lex_state = 11},
  [10] = {.lex_state = 11},
  [11] = {.lex_state = 11},
  [12] = {.lex_state = 11},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 11},
  [17] = {.lex_state = 11},
  [18] = {.lex_state = 11},
  [19] = {.lex_state = 11},
  [20] = {.lex_state = 11},
  [21] = {.lex_state = 11},
  [22] = {.lex_state = 11},
  [23] = {.lex_state = 11},
  [24] = {.lex_state = 11},
  [25] = {.lex_state = 11},
  [26] = {.lex_state = 11},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 11},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 11},
  [34] = {.lex_state = 11},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 11},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 11},
  [45] = {.lex_state = 11},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_preserved] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_min] = ACTIONS(1),
    [anon_sym_max] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_EQ_EQ_GT] = ACTIONS(1),
    [anon_sym_LT_EQ_EQ] = ACTIONS(1),
    [anon_sym_TILDE] = ACTIONS(1),
    [sym_label] = ACTIONS(1),
    [sym_signed_integer] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_source_file] = STATE(54),
    [sym_preserved_directive] = STATE(2),
    [sym_objective] = STATE(4),
    [sym_objective_type] = STATE(29),
    [sym__constraint] = STATE(5),
    [sym_constraint_labelled] = STATE(5),
    [sym_constraint_unlabelled] = STATE(5),
    [sym_xpb_relational_operator] = STATE(52),
    [sym_reification] = STATE(12),
    [sym_sum] = STATE(40),
    [sym_weighted_term] = STATE(26),
    [sym_coefficient] = STATE(41),
    [sym_literal] = STATE(36),
    [sym_variable] = STATE(15),
    [aux_sym_source_file_repeat1] = STATE(5),
    [aux_sym_reification_repeat1] = STATE(27),
    [aux_sym_sum_repeat1] = STATE(26),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_preserved] = ACTIONS(9),
    [anon_sym_min] = ACTIONS(11),
    [anon_sym_max] = ACTIONS(11),
    [anon_sym_GT_EQ] = ACTIONS(13),
    [anon_sym_LT_EQ] = ACTIONS(13),
    [anon_sym_EQ] = ACTIONS(13),
    [anon_sym_TILDE] = ACTIONS(15),
    [sym_label] = ACTIONS(17),
    [sym_signed_integer] = ACTIONS(19),
    [sym_comment] = ACTIONS(3),
  },
  [2] = {
    [sym_objective] = STATE(6),
    [sym_objective_type] = STATE(29),
    [sym__constraint] = STATE(3),
    [sym_constraint_labelled] = STATE(3),
    [sym_constraint_unlabelled] = STATE(3),
    [sym_xpb_relational_operator] = STATE(52),
    [sym_reification] = STATE(12),
    [sym_sum] = STATE(40),
    [sym_weighted_term] = STATE(26),
    [sym_coefficient] = STATE(41),
    [sym_literal] = STATE(36),
    [sym_variable] = STATE(15),
    [aux_sym_source_file_repeat1] = STATE(3),
    [aux_sym_reification_repeat1] = STATE(27),
    [aux_sym_sum_repeat1] = STATE(26),
    [ts_builtin_sym_end] = ACTIONS(21),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_min] = ACTIONS(11),
    [anon_sym_max] = ACTIONS(11),
    [anon_sym_GT_EQ] = ACTIONS(13),
    [anon_sym_LT_EQ] = ACTIONS(13),
    [anon_sym_EQ] = ACTIONS(13),
    [anon_sym_TILDE] = ACTIONS(15),
    [sym_label] = ACTIONS(17),
    [sym_signed_integer] = ACTIONS(19),
    [sym_comment] = ACTIONS(3),
  },
  [3] = {
    [sym__constraint] = STATE(8),
    [sym_constraint_labelled] = STATE(8),
    [sym_constraint_unlabelled] = STATE(8),
    [sym_xpb_relational_operator] = STATE(52),
    [sym_reification] = STATE(12),
    [sym_sum] = STATE(40),
    [sym_weighted_term] = STATE(26),
    [sym_coefficient] = STATE(41),
    [sym_literal] = STATE(36),
    [sym_variable] = STATE(15),
    [aux_sym_source_file_repeat1] = STATE(8),
    [aux_sym_reification_repeat1] = STATE(27),
    [aux_sym_sum_repeat1] = STATE(26),
    [ts_builtin_sym_end] = ACTIONS(23),
    [sym_identifier] = ACTIONS(25),
    [anon_sym_GT_EQ] = ACTIONS(13),
    [anon_sym_LT_EQ] = ACTIONS(13),
    [anon_sym_EQ] = ACTIONS(13),
    [anon_sym_TILDE] = ACTIONS(15),
    [sym_label] = ACTIONS(17),
    [sym_signed_integer] = ACTIONS(19),
    [sym_comment] = ACTIONS(3),
  },
  [4] = {
    [sym__constraint] = STATE(3),
    [sym_constraint_labelled] = STATE(3),
    [sym_constraint_unlabelled] = STATE(3),
    [sym_xpb_relational_operator] = STATE(52),
    [sym_reification] = STATE(12),
    [sym_sum] = STATE(40),
    [sym_weighted_term] = STATE(26),
    [sym_coefficient] = STATE(41),
    [sym_literal] = STATE(36),
    [sym_variable] = STATE(15),
    [aux_sym_source_file_repeat1] = STATE(3),
    [aux_sym_reification_repeat1] = STATE(27),
    [aux_sym_sum_repeat1] = STATE(26),
    [ts_builtin_sym_end] = ACTIONS(21),
    [sym_identifier] = ACTIONS(25),
    [anon_sym_GT_EQ] = ACTIONS(13),
    [anon_sym_LT_EQ] = ACTIONS(13),
    [anon_sym_EQ] = ACTIONS(13),
    [anon_sym_TILDE] = ACTIONS(15),
    [sym_label] = ACTIONS(17),
    [sym_signed_integer] = ACTIONS(19),
    [sym_comment] = ACTIONS(3),
  },
  [5] = {
    [sym__constraint] = STATE(8),
    [sym_constraint_labelled] = STATE(8),
    [sym_constraint_unlabelled] = STATE(8),
    [sym_xpb_relational_operator] = STATE(52),
    [sym_reification] = STATE(12),
    [sym_sum] = STATE(40),
    [sym_weighted_term] = STATE(26),
    [sym_coefficient] = STATE(41),
    [sym_literal] = STATE(36),
    [sym_variable] = STATE(15),
    [aux_sym_source_file_repeat1] = STATE(8),
    [aux_sym_reification_repeat1] = STATE(27),
    [aux_sym_sum_repeat1] = STATE(26),
    [ts_builtin_sym_end] = ACTIONS(21),
    [sym_identifier] = ACTIONS(25),
    [anon_sym_GT_EQ] = ACTIONS(13),
    [anon_sym_LT_EQ] = ACTIONS(13),
    [anon_sym_EQ] = ACTIONS(13),
    [anon_sym_TILDE] = ACTIONS(15),
    [sym_label] = ACTIONS(17),
    [sym_signed_integer] = ACTIONS(19),
    [sym_comment] = ACTIONS(3),
  },
  [6] = {
    [sym__constraint] = STATE(7),
    [sym_constraint_labelled] = STATE(7),
    [sym_constraint_unlabelled] = STATE(7),
    [sym_xpb_relational_operator] = STATE(52),
    [sym_reification] = STATE(12),
    [sym_sum] = STATE(40),
    [sym_weighted_term] = STATE(26),
    [sym_coefficient] = STATE(41),
    [sym_literal] = STATE(36),
    [sym_variable] = STATE(15),
    [aux_sym_source_file_repeat1] = STATE(7),
    [aux_sym_reification_repeat1] = STATE(27),
    [aux_sym_sum_repeat1] = STATE(26),
    [ts_builtin_sym_end] = ACTIONS(23),
    [sym_identifier] = ACTIONS(25),
    [anon_sym_GT_EQ] = ACTIONS(13),
    [anon_sym_LT_EQ] = ACTIONS(13),
    [anon_sym_EQ] = ACTIONS(13),
    [anon_sym_TILDE] = ACTIONS(15),
    [sym_label] = ACTIONS(17),
    [sym_signed_integer] = ACTIONS(19),
    [sym_comment] = ACTIONS(3),
  },
  [7] = {
    [sym__constraint] = STATE(8),
    [sym_constraint_labelled] = STATE(8),
    [sym_constraint_unlabelled] = STATE(8),
    [sym_xpb_relational_operator] = STATE(52),
    [sym_reification] = STATE(12),
    [sym_sum] = STATE(40),
    [sym_weighted_term] = STATE(26),
    [sym_coefficient] = STATE(41),
    [sym_literal] = STATE(36),
    [sym_variable] = STATE(15),
    [aux_sym_source_file_repeat1] = STATE(8),
    [aux_sym_reification_repeat1] = STATE(27),
    [aux_sym_sum_repeat1] = STATE(26),
    [ts_builtin_sym_end] = ACTIONS(27),
    [sym_identifier] = ACTIONS(25),
    [anon_sym_GT_EQ] = ACTIONS(13),
    [anon_sym_LT_EQ] = ACTIONS(13),
    [anon_sym_EQ] = ACTIONS(13),
    [anon_sym_TILDE] = ACTIONS(15),
    [sym_label] = ACTIONS(17),
    [sym_signed_integer] = ACTIONS(19),
    [sym_comment] = ACTIONS(3),
  },
  [8] = {
    [sym__constraint] = STATE(8),
    [sym_constraint_labelled] = STATE(8),
    [sym_constraint_unlabelled] = STATE(8),
    [sym_xpb_relational_operator] = STATE(52),
    [sym_reification] = STATE(12),
    [sym_sum] = STATE(40),
    [sym_weighted_term] = STATE(26),
    [sym_coefficient] = STATE(41),
    [sym_literal] = STATE(36),
    [sym_variable] = STATE(15),
    [aux_sym_source_file_repeat1] = STATE(8),
    [aux_sym_reification_repeat1] = STATE(27),
    [aux_sym_sum_repeat1] = STATE(26),
    [ts_builtin_sym_end] = ACTIONS(29),
    [sym_identifier] = ACTIONS(31),
    [anon_sym_GT_EQ] = ACTIONS(34),
    [anon_sym_LT_EQ] = ACTIONS(34),
    [anon_sym_EQ] = ACTIONS(34),
    [anon_sym_TILDE] = ACTIONS(37),
    [sym_label] = ACTIONS(40),
    [sym_signed_integer] = ACTIONS(43),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_TILDE,
    ACTIONS(19), 1,
      sym_signed_integer,
    ACTIONS(25), 1,
      sym_identifier,
    STATE(15), 1,
      sym_variable,
    STATE(16), 1,
      sym_reification,
    STATE(27), 1,
      aux_sym_reification_repeat1,
    STATE(36), 1,
      sym_literal,
    STATE(41), 1,
      sym_coefficient,
    STATE(45), 1,
      sym_sum,
    STATE(50), 1,
      sym_relational_operator,
    ACTIONS(46), 2,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    STATE(26), 2,
      sym_weighted_term,
      aux_sym_sum_repeat1,
  [42] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(50), 3,
      anon_sym_min,
      anon_sym_max,
      sym_identifier,
    ACTIONS(48), 7,
      ts_builtin_sym_end,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_TILDE,
      sym_label,
      sym_signed_integer,
  [60] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(54), 3,
      anon_sym_min,
      anon_sym_max,
      sym_identifier,
    ACTIONS(52), 7,
      ts_builtin_sym_end,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_TILDE,
      sym_label,
      sym_signed_integer,
  [78] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      sym_signed_integer,
    STATE(33), 1,
      sym_sum,
    STATE(41), 1,
      sym_coefficient,
    STATE(49), 1,
      sym_xpb_relational_operator,
    STATE(26), 2,
      sym_weighted_term,
      aux_sym_sum_repeat1,
    ACTIONS(13), 3,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
  [103] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(58), 2,
      anon_sym_LT_EQ,
      anon_sym_EQ,
    ACTIONS(56), 7,
      anon_sym_SEMI,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ_GT,
      anon_sym_LT_EQ_EQ,
      anon_sym_TILDE,
      sym_identifier,
      sym_signed_integer,
  [120] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(62), 2,
      anon_sym_LT_EQ,
      anon_sym_EQ,
    ACTIONS(60), 7,
      anon_sym_SEMI,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ_GT,
      anon_sym_LT_EQ_EQ,
      anon_sym_TILDE,
      sym_identifier,
      sym_signed_integer,
  [137] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(66), 2,
      anon_sym_LT_EQ,
      anon_sym_EQ,
    ACTIONS(64), 7,
      anon_sym_SEMI,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ_GT,
      anon_sym_LT_EQ_EQ,
      anon_sym_TILDE,
      sym_identifier,
      sym_signed_integer,
  [154] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      sym_signed_integer,
    STATE(41), 1,
      sym_coefficient,
    STATE(44), 1,
      sym_sum,
    STATE(47), 1,
      sym_relational_operator,
    ACTIONS(46), 2,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    STATE(26), 2,
      sym_weighted_term,
      aux_sym_sum_repeat1,
  [178] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 8,
      ts_builtin_sym_end,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_TILDE,
      sym_identifier,
      sym_label,
      sym_signed_integer,
  [192] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 8,
      ts_builtin_sym_end,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_TILDE,
      sym_identifier,
      sym_label,
      sym_signed_integer,
  [206] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 1,
      sym_signed_integer,
    STATE(41), 1,
      sym_coefficient,
    STATE(19), 2,
      sym_weighted_term,
      aux_sym_sum_repeat1,
    ACTIONS(72), 4,
      anon_sym_SEMI,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
  [226] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 8,
      ts_builtin_sym_end,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_TILDE,
      sym_identifier,
      sym_label,
      sym_signed_integer,
  [240] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 8,
      ts_builtin_sym_end,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_TILDE,
      sym_identifier,
      sym_label,
      sym_signed_integer,
  [254] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(81), 8,
      ts_builtin_sym_end,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_TILDE,
      sym_identifier,
      sym_label,
      sym_signed_integer,
  [268] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 8,
      ts_builtin_sym_end,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_TILDE,
      sym_identifier,
      sym_label,
      sym_signed_integer,
  [282] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 8,
      ts_builtin_sym_end,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_TILDE,
      sym_identifier,
      sym_label,
      sym_signed_integer,
  [296] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 8,
      ts_builtin_sym_end,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_TILDE,
      sym_identifier,
      sym_label,
      sym_signed_integer,
  [310] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      sym_signed_integer,
    STATE(41), 1,
      sym_coefficient,
    STATE(19), 2,
      sym_weighted_term,
      aux_sym_sum_repeat1,
    ACTIONS(89), 3,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
  [329] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_TILDE,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(91), 1,
      anon_sym_EQ_EQ_GT,
    STATE(15), 1,
      sym_variable,
    STATE(28), 2,
      sym_literal,
      aux_sym_reification_repeat1,
  [349] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      sym_identifier,
    ACTIONS(96), 1,
      anon_sym_EQ_EQ_GT,
    ACTIONS(98), 1,
      anon_sym_TILDE,
    STATE(15), 1,
      sym_variable,
    STATE(28), 2,
      sym_literal,
      aux_sym_reification_repeat1,
  [369] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      sym_signed_integer,
    STATE(30), 1,
      sym_coefficient,
    STATE(46), 1,
      sym_sum,
    STATE(32), 2,
      sym_weighted_term,
      aux_sym_sum_repeat1,
  [386] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_TILDE,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(101), 1,
      anon_sym_SEMI,
    STATE(15), 1,
      sym_variable,
    STATE(31), 1,
      sym_literal,
  [405] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 5,
      anon_sym_SEMI,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      sym_signed_integer,
  [416] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 1,
      anon_sym_SEMI,
    ACTIONS(105), 1,
      sym_signed_integer,
    STATE(41), 1,
      sym_coefficient,
    STATE(19), 2,
      sym_weighted_term,
      aux_sym_sum_repeat1,
  [433] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(51), 1,
      sym_xpb_relational_operator,
    ACTIONS(13), 3,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
  [445] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 4,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      sym_signed_integer,
  [455] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 1,
      sym_identifier,
    ACTIONS(113), 1,
      anon_sym_SEMI,
    STATE(35), 2,
      sym_variable,
      aux_sym_preserved_directive_repeat1,
  [469] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 1,
      anon_sym_LT_EQ_EQ,
    ACTIONS(115), 3,
      anon_sym_EQ_EQ_GT,
      anon_sym_TILDE,
      sym_identifier,
  [481] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(117), 1,
      anon_sym_SEMI,
    STATE(35), 2,
      sym_variable,
      aux_sym_preserved_directive_repeat1,
  [495] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(119), 1,
      anon_sym_SEMI,
    STATE(35), 2,
      sym_variable,
      aux_sym_preserved_directive_repeat1,
  [509] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(121), 1,
      anon_sym_COLON,
    STATE(38), 2,
      sym_variable,
      aux_sym_preserved_directive_repeat1,
  [523] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(49), 1,
      sym_xpb_relational_operator,
    ACTIONS(13), 3,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
  [535] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_TILDE,
    ACTIONS(25), 1,
      sym_identifier,
    STATE(15), 1,
      sym_variable,
    STATE(31), 1,
      sym_literal,
  [551] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 3,
      anon_sym_SEMI,
      anon_sym_TILDE,
      sym_identifier,
  [560] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      sym_identifier,
    STATE(37), 2,
      sym_variable,
      aux_sym_preserved_directive_repeat1,
  [571] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(53), 1,
      sym_relational_operator,
    ACTIONS(46), 2,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [582] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(47), 1,
      sym_relational_operator,
    ACTIONS(46), 2,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [593] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      sym_signed_integer,
    ACTIONS(101), 1,
      anon_sym_SEMI,
    STATE(60), 1,
      sym_coefficient,
  [606] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      sym_signed_integer,
    STATE(61), 1,
      sym_coefficient,
  [616] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      sym_identifier,
    STATE(14), 1,
      sym_variable,
  [626] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      sym_signed_integer,
    STATE(62), 1,
      sym_coefficient,
  [636] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      sym_signed_integer,
    STATE(56), 1,
      sym_coefficient,
  [646] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      sym_signed_integer,
    STATE(63), 1,
      sym_coefficient,
  [656] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      sym_signed_integer,
    STATE(57), 1,
      sym_coefficient,
  [666] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      sym_signed_integer,
    STATE(65), 1,
      sym_coefficient,
  [676] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      ts_builtin_sym_end,
  [683] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 1,
      sym_signed_integer,
  [690] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 1,
      anon_sym_SEMI,
  [697] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 1,
      anon_sym_SEMI,
  [704] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 1,
      sym_signed_integer,
  [711] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 1,
      sym_signed_integer,
  [718] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(137), 1,
      anon_sym_SEMI,
  [725] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      anon_sym_SEMI,
  [732] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 1,
      anon_sym_SEMI,
  [739] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 1,
      anon_sym_SEMI,
  [746] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(145), 1,
      anon_sym_COLON,
  [753] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 1,
      anon_sym_SEMI,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(9)] = 0,
  [SMALL_STATE(10)] = 42,
  [SMALL_STATE(11)] = 60,
  [SMALL_STATE(12)] = 78,
  [SMALL_STATE(13)] = 103,
  [SMALL_STATE(14)] = 120,
  [SMALL_STATE(15)] = 137,
  [SMALL_STATE(16)] = 154,
  [SMALL_STATE(17)] = 178,
  [SMALL_STATE(18)] = 192,
  [SMALL_STATE(19)] = 206,
  [SMALL_STATE(20)] = 226,
  [SMALL_STATE(21)] = 240,
  [SMALL_STATE(22)] = 254,
  [SMALL_STATE(23)] = 268,
  [SMALL_STATE(24)] = 282,
  [SMALL_STATE(25)] = 296,
  [SMALL_STATE(26)] = 310,
  [SMALL_STATE(27)] = 329,
  [SMALL_STATE(28)] = 349,
  [SMALL_STATE(29)] = 369,
  [SMALL_STATE(30)] = 386,
  [SMALL_STATE(31)] = 405,
  [SMALL_STATE(32)] = 416,
  [SMALL_STATE(33)] = 433,
  [SMALL_STATE(34)] = 445,
  [SMALL_STATE(35)] = 455,
  [SMALL_STATE(36)] = 469,
  [SMALL_STATE(37)] = 481,
  [SMALL_STATE(38)] = 495,
  [SMALL_STATE(39)] = 509,
  [SMALL_STATE(40)] = 523,
  [SMALL_STATE(41)] = 535,
  [SMALL_STATE(42)] = 551,
  [SMALL_STATE(43)] = 560,
  [SMALL_STATE(44)] = 571,
  [SMALL_STATE(45)] = 582,
  [SMALL_STATE(46)] = 593,
  [SMALL_STATE(47)] = 606,
  [SMALL_STATE(48)] = 616,
  [SMALL_STATE(49)] = 626,
  [SMALL_STATE(50)] = 636,
  [SMALL_STATE(51)] = 646,
  [SMALL_STATE(52)] = 656,
  [SMALL_STATE(53)] = 666,
  [SMALL_STATE(54)] = 676,
  [SMALL_STATE(55)] = 683,
  [SMALL_STATE(56)] = 690,
  [SMALL_STATE(57)] = 697,
  [SMALL_STATE(58)] = 704,
  [SMALL_STATE(59)] = 711,
  [SMALL_STATE(60)] = 718,
  [SMALL_STATE(61)] = 725,
  [SMALL_STATE(62)] = 732,
  [SMALL_STATE(63)] = 739,
  [SMALL_STATE(64)] = 746,
  [SMALL_STATE(65)] = 753,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preserved_directive, 3, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_preserved_directive, 3, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preserved_directive, 4, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_preserved_directive, 4, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 1, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 1, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 2, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_literal, 2, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 1, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_literal, 1, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constraint_labelled, 5, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constraint_labelled, 4, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_sum_repeat1, 2, 0, 0),
  [74] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sum_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constraint_unlabelled, 3, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_objective, 3, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_objective, 4, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constraint_unlabelled, 4, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constraint_unlabelled, 5, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constraint_labelled, 6, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sum, 1, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [93] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_reification_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_reification_repeat1, 2, 0, 0),
  [98] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_reification_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_weighted_term, 2, 0, 0),
  [105] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_sum, 1, 0, 0), SHIFT(42),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_reification, 2, 0, 0),
  [110] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_preserved_directive_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_preserved_directive_repeat1, 2, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_reification_repeat1, 1, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_coefficient, 1, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_xpb_relational_operator, 1, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_objective_type, 2, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_relational_operator, 1, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_opb(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
